server {
    listen 80;
    server_name xx.h2omol.com;
    return 301 https://$host$request_uri;
}

upstream fastapi_backend {
    server host.docker.internal:8001;
    keepalive 32; # Nginx 워커당 유지할 유휴 keepalive 연결 수
    keepalive_timeout 30s; # 백엔드와 연결을 유지할 최대 시간
}

server {
    listen 443 ssl;
    server_name uniP-ICT.h2omol.com;

    keepalive_timeout 75s 15s;
    keepalive_requests 1000; # 하나의 연결당 최대 요청 수 (기본값 1000)


    include /etc/nginx/mime.types;

    location / {
        root /var/www/unip-ict;
        index index.html;
        try_files $uri $uri/ /index.html; # Svelte 라우팅 대응 필수 설정
    }

    location /api {
        proxy_pass http://fastapi_backend; # FastAPI 백엔드 연동

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
