# 1. HTTP to HTTPS Redirect
server {
    listen 80;
    server_name xxx.com;
    return 301 https://$host$request_uri;
}

# 2. HTTPS Proxy for FastAPI
server {
    listen 443 ssl;   # Added 'ssl' here
    server_name xxx.com; 

    location / {
        proxy_pass http://host.docker.internal:xxxx; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# MQTTS용.
stream {
    server {
        listen 8883 ssl;

        # Nginx와 브로커가 같은 docker-compose에 있다면 서비스 이름 사용 가능하지만, 아니라서 이렇게 함.
        proxy_pass host.docker.internal:1883;
    }
}
